version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2021.07
    steps:
      - checkout
      # Whatever you want to do
      - run:
          command: |
            docker --version
            sudo systemctl start docker
            docker run -t owasp/zap2docker-stable zap-baseline.py -t https://www.itsecgames.com/
  