version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2021.07
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Zap Scanning
          command: |
            pwd
            sudo mkdir -p out
            ls -l
            sudo chmod 777 out
            ls -l && echo "Full Access Granted"
            (
              docker run -v $(pwd)/out:/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py \
              -t http://www.itsecgames.com/ -d -r testreport.html || \
              if [ $? -ne 1 ]; then exit 0; else exit 1; fi; 
            )