version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2021.07
    steps:
      - setup_remote_docker
      - checkout
      # Whatever you want to do
      #- run:
      #    command: |
      #      docker --version
      #      sudo systemctl start docker
      #      docker run -t owasp/zap2docker-stable zap-baseline.py -t https://www.itsecgames.com/
      #    name: Docker Trial
      - run:
          name: Zap Scanning
          command: |
            pwd
            sudo mkdir -p out
            ls -l
            (
              docker run -v $(pwd)/out:/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py \
              -t http://www.itsecgames.com/ -d -r testreport.html || \
              if [ $? -ne 1 ]; then exit 0; else exit 1; fi; 
            )