name: TruffleHog

on:
  push:
    branches: [ '*' ]

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Scan for secrets
        uses: trufflesecurity/trufflehog@main
        with:
          # Options to pass to TruffleHog
          args: '--exclude_paths node_modules/'

      - name: Print scan results
        run: cat trufflehog_report.json
